### ISSUE TITLE
Missing projects in dependency_track_project_vulnerabilities

### ISSUE THREAD

**Issue by sergioasantiago** [jetstack/dependency-track-exporter#48]
I'm trying to run dependency-track-exporter with my dependency-track installation.
We have more than 400 projects, and seems like the pagination is not working since I cannot find many projects in exported metrics.

**Comment by ribbybibby** [comment]
I'm going to try and investigate this today.

Do you see any errors in the logs?

**Comment by ribbybibby** [comment]
https://github.com/DependencyTrack/client-go/pull/1 - the issue seems to be in the upstream package. I've submitted a PR to fix it.

**Comment by sergioasantiago** [comment]
I have upgraded to the latest. Looks like it is now fetching all the projects, but I'm getting bunch of these errors:

```
ts=2023-02-06T16:57:45.506Z caller=main.go:47 level=info msg="Starting dependency_track_exporter (version=0.1.2, branch=HEAD, revision=7207956da7db4062cb108e4ad5d6819c7c133150)"
ts=2023-02-06T16:57:45.506Z caller=main.go:48 level=info msg="Build context (go=go1.19.5, platform=linux/amd64, user=, date=2023-02-06T16:04:32Z)"
ts=2023-02-06T16:57:45.506Z caller=tls_config.go:232 level=info msg="Listening on" address=[::]:9916
ts=2023-02-06T16:57:45.506Z caller=tls_config.go:235 level=info msg="TLS is disabled." http2=false address=[::]:9916
ts=2023-02-06T16:58:51.339Z caller=exporter.go:39 level=error err="Get \"https://dependencytrack.localhost/api/v1/project?pageNumber=12&pageSize=50\": context canceled"
ts=2023-02-06T16:58:54.121Z caller=exporter.go:39 level=error err="Get \"https://dependencytrack.localhost/api/v1/project?pageNumber=12&pageSize=50\": context canceled"
ts=2023-02-06T16:59:04.121Z caller=exporter.go:39 level=error err="Get \"https://dependencytrack.localhost/api/v1/project?pageNumber=12&pageSize=50\": context canceled"
ts=2023-02-06T16:59:14.121Z caller=exporter.go:39 level=error err="Get \"https://dependencytrack.localhost/api/v1/project?pageNumber=12&pageSize=50\": context canceled"
ts=2023-02-06T16:59:24.121Z caller=exporter.go:39 level=error err="Get \"https://dependencytrack.localhost/api/v1/project?pageNumber=12&pageSize=50\": context canceled"
ts=2023-02-06T16:59:34.121Z caller=exporter.go:39 level=error err="Get \"https://dependencytrack.localhost/api/v1/project?pageNumber=11&pageSize=50\": context canceled"
``
`

**Comment by ribbybibby** [comment]
Are there any timeout errors in the logs of your Prometheus instance? I think this might be down to the request duration exceeding the `scrape_timeout` (default is 10s). If that's the case then try to increase the `scrape_timeout`.

If that's the problem then I'd suggest moving any further discussion to https://github.com/jetstack/dependency-track-exporter/issues/30, where this is tracked.

**Comment by sergioasantiago** [comment]
Ah I see. The issue is that I'm using `/metrics` as the health check url and k8s is killing the pod due to timeout. Is there a healthz endpoint that I could use instead?

**Comment by ribbybibby** [comment]
You could just use `/` which should return a 200.
