### ISSUE TITLE
Dockerfile not working

### ISSUE THREAD

**Issue by mieliespoor** [jetstack/dependency-track-exporter#70]
Trying to get the dockerfile working locally to test this out and see how it will work for us. 

When I do `docker run dependencytrackexporter:latest`, I get the error `exec /dependency-track-exporter: no such file or directory`.

**Comment by ribbybibby** [comment]
Ah, we need to build the binary with CGO disabled.

This should fix it: https://github.com/jetstack/dependency-track-exporter/pull/71.

**Comment by ribbybibby** [comment]
Closed by #71 .
